import { Providers } from "./providers";
import "./globals.css";
import Nav from "@/components/navigation/Nav";

export const metadata = {
  title: "Just Another Generic Note Taking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
