import { Providers } from "./providers";
import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/ui/navigation";

export const metadata = {
  title: "Just Another Generic Note Taking App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} prose prose-invert prose-neutral w-full max-w-full`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
